export const SelectorButtonStyles: React.CSSProperties = {
  width: '40px',
  height: '32px',
  backgroundColor: '#000000',
  border: 'none',
  color: '#FFFFFF',
  fontSize: '24px',
  outline: 'none',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: '4px',
}
// export const BidButtonStyles:React.CSSProperties={
//     width:'144px',
//     height:'47px',
//     backgroundColor:' #000000',
//     border:'none',
//     color:'#FFFFFF',
//     fontSize:'18px',
//     outline:'none',
//     cursor:'pointer',
//     display:'flex',
//     alignItems:'center',
//     justifyContent:'center',
//     borderRadius:'4px',
// }
// export const StakeButtonStyles:React.CSSProperties={
//     width:'145px',
//     height:'47px',
//     backgroundColor:'transparent',
//     border:'1px solid rgba(255, 255, 255, 1)',
//     color:'white',
//     fontSize:'24px',
//     outline:'none',
//     cursor:'pointer',
//     display:'flex',
//     alignItems:'center',
//     justifyContent:'center',
//     borderRadius:'4px'
// }
