export const SelectorButtonStyles: React.CSSProperties = {
  width: '40px',
  height: '32px',
  backgroundColor: '#FFFFFF',
  border: 'none',
  color: '#000000',
  fontSize: '24px',
  outline: 'none',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: '4px',
}
export const BuyButtonStyles: React.CSSProperties = {
  width: '145px',
  height: '47px',
  backgroundColor: '#FFFFFF',
  border: 'none',
  color: '#000000',
  fontSize: '24px',
  outline: 'none',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: '4px',
  marginBottom: '16px',
}
export const StakeButtonStyles: React.CSSProperties = {
  width: '145px',
  height: '47px',
  backgroundColor: 'transparent',
  border: '1px solid rgba(255, 255, 255, 1)',
  color: 'white',
  fontSize: '24px',
  outline: 'none',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: '4px',
}
